version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: redcare-ha-dev
    command: npm run dev
    ports:
      - '4000:4000'
    environment:
      NODE_ENV: development
      PORT: 4000
      GITHUB_BASE_URL: https://api.github.com
      GITHUB_TOKEN: ${GITHUB_TOKEN:-}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
